### ISSUE TITLE
Include `rcppmath` utilities in features document

### ISSUE THREAD

**Issue by aprotyas** [ros2/rcpputils#134]
The package would benefit from inclusion of the clamp and rolling mean accumulator headers found under `rcppmath` in the [docs/FEATURES.md](https://github.com/ros2/rcpputils/blob/master/docs/FEATURES.md) document. Another option could be to author a separate FEATURES document exclusive to `rcppmath`'s scope, since these headers are currently not mentioned in the README or in the FEATURES document.

**Comment by fujitatomoya** [comment]
sounds good to me. i think that we could add doc in [docs/FEATURES.md](https://github.com/ros2/rcpputils/blob/master/docs/FEATURES.md).
