### ISSUE TITLE
Compilation error with rolling mean accumulator

### ISSUE THREAD

**Issue by Octogonapus** [ros2/rcpputils#146]
I ran into this compiler error when building ROS 2 galactic on Fedora 34: https://pastebin.com/raw/3Zj1wrDY
The issue does not occur on v2.2.0 (9cad93ee6ee700007ed19036aeb1cc5ac54bba00).

My build command: `colcon build --symlink-install --packages-up-to rcpputils`.
GCC version: `gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)`
`uname -r`: `5.13.16-200.fc34.x86_64`

**Comment by clalancette** [comment]
> This is confusing. Not recognizing `size_t`? Or any data members of the class? I want to say the rolling mean accumulator class isn't the problem here, but I don't know what is.

Yeah, agreed.  Something very weird is going on in that setup.

For what it is worth, the latest rcpputils code compiles just fine for me on Fedora 33 (and on Ubuntu 20.04, which is what we run CI on).  Can you give a lot more detail about your setup, how you cloned the repositories, versions of the repositories you have checked out, etc?

**Comment by Octogonapus** [comment]
I set up the repos following [this guide](https://docs.ros.org/en/galactic/Installation/Ubuntu-Development-Setup.html#galactic-linux-dev-get-ros2-code)
Reproduced here:
```
mkdir -p ros2_galactic/src
cd ros2_galactic
wget https://raw.githubusercontent.com/ros2/ros2/galactic/ros2.repos
vcs import src < ros2.repos

sudo rosdep init
rosdep update
rosdep install --from-paths src --ignore-src --rosdistro galactic -y --skip-keys "console_bridge fastcdr fastrtps rti-connext-dds-5.3.1 urdfdom_headers"

colcon build --symlink-install
```

Additional dependencies (run before the above code) were installed following [this guide](https://docs.ros.org/en/galactic/Installation/Fedora-Development-Setup.html)

Output of `colcon info`: https://pastebin.com/raw/dZ4heWCP
cmake version `3.20.5`
git bisect points to `dd5fe5e3ba92a40271246fb841798f5abdf8ab79` as the first bad commit.

I can fix the error by including `#include <cstddef>` in `include/rcppmath/rolling_mean_accumulator.hpp`.

**Comment by clalancette** [comment]
> I can fix the error by including `#include <cstddef>` in `include/rcppmath/rolling_mean_accumulator.hpp`. Sounds like this compiles fine on GCC 10 (Fedora 33) but not GCC 11 (Fedora 34).

Ah yeah, maybe that is it.  Mind submitting a PR to add `#include <cstddef>` at the top of the file?

**Comment by Octogonapus** [comment]
I will submit a PR.

**Comment by aprotyas** [comment]
> > I can fix the error by including `#include <cstddef>` in `include/rcppmath/rolling_mean_accumulator.hpp`. Sounds like this compiles fine on GCC 10 (Fedora 33) but not GCC 11 (Fedora 34).
> 
> Ah yeah, maybe that is it. Mind submitting a PR to add `#include <cstddef>` at the top of the file?

Can anyone explain why this was required for the rolling mean class? There's uses of `size_t` in other headers too...

**Comment by Octogonapus** [comment]
The only other use of `size_t` is in [test_split.cpp](https://github.com/ros2/rcpputils/blob/9cad93ee6ee700007ed19036aeb1cc5ac54bba00/test/test_split.cpp#L267) which includes [split.hpp](https://github.com/ros2/rcpputils/blob/master/include/rcpputils/split.hpp#L41), which then includes the `string` header. The `string` header includes `stddef.h`, which provides `size_t`.
