### ISSUE TITLE
Environment helpers: function to set environment variable?

### ISSUE THREAD

**Issue by aprotyas** [ros2/rcpputils#149]
## Feature request

It would be nice to have a way to set environment variables. I have at least one use-case in https://github.com/ros2/domain_bridge/pull/60#discussion_r740617226.

#### Feature description
A function that allows setting a named environment variable; essentially a dual of `rcpputils::get_env_var`.

#### Implementation considerations
It could be implemented exactly how `rcpputils::get_env_var` is implemented, by invoking the corresponding `rcutils` environment helper function.

One approach:
```cpp
bool set_env_var(const char * env_var, const char * env_value)
{
  if (!rcutils_set_env(env_var, env_value)) {
    std::string err = rcutils_get_error_string().str;
    // Resetting the error state since error string has been extracted
    rcutils_reset_error();
    throw std::runtime_error(err);
  }
  return true;
}
```

**Comment by aprotyas** [comment]
I've already opened #150 with my own implementation, but if that needs changing, feel free to open a separate PR to close this issue.

**Comment by fujitatomoya** [comment]
this makes sense to me, i am good to go with this.
