### ISSUE TITLE
Try introducing cxxopts as a vendor package and demonstrate in demo_nodes_cpp

### ISSUE THREAD

**Issue by emersonknapp** [ros2/rcpputils#15]
This is a placeholder issue to follow through on discussion here https://discourse.ros.org/t/introduce-c-commandline-argument-parsing-library/9197 about introducing a common commandline argument parser for C++, to match `argparse` in Python. 

https://github.com/jarro2783/cxxopts looks promising and is a popular repo.

Goal: Expose `cxxopts` as a vendor library, perhaps as a subpackage of this repo, and use it to simplify https://github.com/ros2/demos/blob/master/quality_of_service_demo/rclcpp/src/lifespan.cpp as the proof of usage concept

**Comment by dirk-thomas** [comment]
If there is no reason for `rcpputils` to provide additional helper functionality on top of `cxxopts` it doesn't have to be in this repository but can be hosted in its own `cxxopts_vendor` repository.

Assuming that there is nothing to be done in this repo I will go ahead and close this for now.
