### ISSUE TITLE
Release to Galactic

### ISSUE THREAD

**Issue by bmagyar** [ros2/rcpputils#157]
I'm soooo eager to remove a 100 lines from ros2_controllers, just need a release of Galactic!

![eyes-cute](https://user-images.githubusercontent.com/3524577/148516206-039f7b16-3b12-45fb-b7a2-150f607925b4.gif)

**Comment by clalancette** [comment]
https://github.com/ros/rosdistro/pull/31707 is the release, we'll still need to merge it and then get a sync out with it.

**Comment by bmagyar** [comment]
Thanks!!
