### ISSUE TITLE
Deprecate `rcpputils::fs` in favor of C++17 `std::filesystem`

### ISSUE THREAD

**Issue by emersonknapp** [ros2/rcpputils#164]
Now that it's available, there's no reason to provide a wrapper for the std functionality (IMO).

Related to #125

**Comment by clalancette** [comment]
I agree.

To get there, what would need to happen is the following:
1. Go through the ROS 2 core, changing any uses of `rcpputils::fs` to `std::filesystem`.
2. Mark the various functions and classes in `rcpputils::fs` as deprecated for Iron.
3. Put a release note into the [release page for Iron](https://docs.ros.org/en/rolling/Releases/Release-Iron-Irwini.html).
4. For J-Turtle, remove `rcpputils::fs`

**Comment by MichaelOrlov** [comment]
@clalancette @emersonknapp I remember we had problems on the on RHEL-8 due to the lack of adequate support for `std::filesystem::path(..)`
See https://github.com/ros2/rosbag2/pull/1104 for details.
Has it already been fixed or not an issue anymore?

**Comment by felixf4xu** [comment]
just a heads-up to check the status of this issue :-)

It's not an urgent issue, but I think it's a valid issue.

**Comment by clalancette** [comment]
We are still having issues around https://github.com/ros2/rclcpp/pull/2438, so we can't deprecate it until that is fixed.

**Comment by ahcorde** [comment]
we can close this issue the deprecation is done here https://github.com/ros2/rclcpp/pull/2579.
