### ISSUE TITLE
no match for 'operator==' error

### ISSUE THREAD

**Issue by k-ish0212** [ros2/rcpputils#168]
I've encountered such an error when colcon build in ros2 humble. It looks there's no operator '==' in rcpputils::fs::path. 

>  In file included from /root/xarm/ros2_humble/src/ros/pluginlib/pluginlib/include/pluginlib/class_loader.hpp:334,
                 from /root/xarm/ros2_humble/src/ros/pluginlib/pluginlib/test/utest.cpp:33:
/root/xarm/ros2_humble/src/ros/pluginlib/pluginlib/include/pluginlib/./class_loader_imp.hpp: In member function ‘std::string pluginlib::ClassLoader<T>::getPackageFromPluginXMLFilePath(const string&)’:
/root/xarm/ros2_humble/src/ros/pluginlib/pluginlib/include/pluginlib/./class_loader_imp.hpp:589:39: error: no match for ‘operator==’ (operand types are ‘rcpputils::fs::path’ and ‘rcpputils::fs::path’)
  589 |     if (parent.string().empty() || (p == parent)) {
      |                                     ~ ^~ ~~~~~~
      |                                     |    |
      |                                     |    rcpputils::fs::path
      |                                     rcpputils::fs::path
In file included from /root/xarm/ros2_humble/src/ros/pluginlib/pluginlib/include/pluginlib/class_loader.hpp:334,
                 from /root/xarm/ros2_humble/src/ros/pluginlib/pluginlib/test/unique_ptr_test.cpp:32:
/root/xarm/ros2_humble/src/ros/pluginlib/pluginlib/include/pluginlib/./class_loader_imp.hpp: In member function ‘std::string pluginlib::ClassLoader<T>::getPackageFromPluginXMLFilePath(const string&)’:
/root/xarm/ros2_humble/src/ros/pluginlib/pluginlib/include/pluginlib/./class_loader_imp.hpp:589:39: error: no match for ‘operator==’ (operand types are ‘rcpputils::fs::path’ and ‘rcpputils::fs::path’)
  589 |     if (parent.string().empty() || (p == parent)) {
      |                                     ~ ^~ ~~~~~~
      |                                     |    |
      |                                     |    rcpputils::fs::path
      |                                     rcpputils::fs::path
make[2]: *** [CMakeFiles/pluginlib_utest.dir/build.make:63: CMakeFiles/pluginlib_utest.dir/test/utest.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:187: CMakeFiles/pluginlib_utest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/pluginlib_unique_ptr_test.dir/build.make:63: CMakeFiles/pluginlib_unique_ptr_test.dir/test/unique_ptr_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:243: CMakeFiles/pluginlib_unique_ptr_test.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
>  Failed   <<< pluginlib [2.24s, exited with code 2]
Aborted  <<< rosidl_typesupport_fastrtps_cpp [8.29s] 
Aborted  <<< rcl_logging_spdlog [2.90s]              
Aborted  <<< rcl_yaml_param_parser [7.67s]           
Aborted  <<< rviz_rendering [23.2s]                  
Aborted  <<< rosidl_typesupport_introspection_tests [18.7s]

>  Summary: 141 packages finished [48.2s]
  1 package failed: pluginlib
  5 packages aborted: rcl_logging_spdlog rcl_yaml_param_parser rosidl_typesupport_fastrtps_cpp rosidl_typesupport_introspection_tests rviz_rendering
  1 package had stderr output: pluginlib
  196 packages not processed

Does anyone know how to solve this?

Thank you.

**Comment by christophebedard** [comment]
Make sure you're using the `humble` branch of `rcpputils`: https://github.com/ros2/rcpputils/blob/a7898d98ab684bb5d0cb2c20c823a1b4014fa0dc/include/rcpputils/filesystem_helper.hpp#L342

**Comment by k-ish0212** [comment]
Some big problem exists for working humble on ubuntu20.04... but these are different issues here. I close this issue.

Thank you.

**Comment by christophebedard** [comment]
> Some big problem exists for working humble on ubuntu20.04...

For Humble, you should use Ubuntu 22.04.

**Comment by k-ish0212** [comment]
Ok, I'll try it. Is there any reason ubuntu20 deprecated for humble? In tutorial looks ubuntu20.04 also available. https://docs.ros.org/en/humble/Installation/Alternatives/Ubuntu-Development-Setup.html

**Comment by fujitatomoya** [comment]
Yeah, right it tells that Humble supports Ubuntu 20.04 as Tier 3 platform.

> Tier 3: Ubuntu Linux - Focal (20.04) 64-bit

this means that `community support` only, we do not run CI for that.
you can find the definition about `support tiers` here, https://www.ros.org/reps/rep-2000.html#support-tiers.

CC: @ros2/team
