### ISSUE TITLE
Progress toward Quality Level 1

### ISSUE THREAD

**Issue by brawner** [ros2/rcpputils#39]
This issue tracks the progression of `rcpputils` to Quality Level 1 and a 1.0 version level. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/c2ba03bac23b8f313e47820833fad000dbbe058b/rep-2004.rst). 

* [x] Version Policy
    - Follows ROS Core Quality Declaration
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Follows ROS Core
* [x] PRs automatically tested on Jenkins

Documentation
* [x] Per-feature documentation. 
    - Features still needing documentation on README.md or equivalent (`endian.hpp`, `filesystem_helper.hpp`, `find_and_replace.hpp`, `find_library.hpp`, `join.hpp`, `split.hpp`, `pointer_traits.hpp`, `visibility_control.hpp`)
* [x] Per-item documentation in public API. 
    - Items need doc blocks (`endian.hpp`, `filesystem_helper.hpp`, `thread_safety_annotations.hpp`, `visibility_control.hpp`)
    - Items needing doc improvements (`join.hpp`)
* [x] Declared set of licenses
* [x] Copyright statement in each source file
    - Incomplete, see https://github.com/ros2/rcpputils/pull/37
* [x] Quality Declaration document (#47)

Testing:
* [x] System tests, which cover "features"
* [x] Tests covering public API
* [x] Code coverage (95%)
    - 60%, see https://github.com/j-rivero/rcpputils/pull/2#issuecomment-581990410
* [x] Performance tests
* [x] Performance test policy: ROS Core
* [x] Package code style: ROS Core
* [x] Uses ament_lint_common

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rcutils
* [x] non-ROS dependencies are equivalent level 1
    - c++ standard library

Platform Support
* [x] Supports all tier 1 platforms

Specific comments:
* `filesystem_helper.hpp` could attempt to include `<filesystem>` and use std::filesystem if possible. It's likely Foxy's supported systems already have `<filesystem>`
* `find_and_replace.hpp` 
    - A regex based solution might have better performance
    - Tests could use more variation
* `find_library.hpp`
    - Could use more tests
* `join.hpp`
    - Doc block's description is a little clunky
    - delim could be an optional parameter with a null default
    - Tests could use more variation of containers and value types
* `pointer_traits.hpp`
    - Tests could use more variation of false cases
* `split.hpp`
    - is inline necessary?
* `thread_safety_annotations.hpp`
    - `#define` statements need documentation
    - Untested defines (`RCPPUTILS_TSA_TRY_ACQUIRE`, `RCPPUTILS_TSA_TRY_ACQUIRE_SHARED`, `RCPPUTILS_TSA_ACQUIRED_BEFORE`, `RCPPUTILS_TSA_ACQUIRED_AFTER`)
* `visibility_control.hpp`
    - Needs tests
    - Needs documentation

**Comment by chapulina** [comment]
Reached level 1: https://github.com/ros2/rcpputils/pull/114
