### ISSUE TITLE
Release for Foxy

### ISSUE THREAD

**Issue by jacobperron** [ros2/rcpputils#59]
We're doing our first round of releases into the ROS Foxy distro and this package should also be tagged and released.

@emersonknapp Let me know if you're able to make the release, or if you'd like me to.

**Comment by thomas-moulard** [comment]
rcpputils is in: http://repo.ros2.org/status_page/foxy_default.html?q=rcpputils

ARMHF and ARM64 builds seems to be pending.

**Comment by jacobperron** [comment]
Thank you!
