### ISSUE TITLE
find_library: Rely on `poco` instead of hand-rolling functionality

### ISSUE THREAD

**Issue by EricCousineau-TRI** [ros2/rcpputils#7]
From discussion in #4

**Comment by clalancette** [comment]
For what it is worth, we decided to go the opposite way and not depend on poco at all in the core.

Given that, I'm going to close this out.  If you feel we should still depend on poco, feel free to reopen.

**Comment by EricCousineau-TRI** [comment]
Sounds good, thanks for the update!
