### ISSUE TITLE
Header-only rcpputils::get_env_var()

### ISSUE THREAD

**Issue by christophebedard** [ros2/rcpputils#82]
Is there any reason why `rcpputils::get_env_var()` (#55) is provided as header-only?

I get "multiple definitions" linking errors if I `#include` the header twice (two different files but same executable). I hope I'm not doing anything wrong, but I don't think I am.

**Comment by Karsten1987** [comment]
I think you're right and the function should be `inline` if header only or as you mentioned be split into header/impl.

**Comment by christophebedard** [comment]
I would vote for a split into header/impl, since this is what `rcutils` does with `rcutils_get_env()`.

If it helps, I can make the change.

**Comment by Karsten1987** [comment]
Would be great if you could come up with a PR.
