### ISSUE TITLE
Adding common math functions

### ISSUE THREAD

**Issue by v-lopez** [ros2/rcpputils#84]
This issue comes from the an issue during ROS2 Control development: https://github.com/ros-controls/ros2_controllers/issues/40

There are some fairly common math operations (in this case [clamp](https://en.cppreference.com/w/cpp/algorithm/clamp)) that are not accessible unless you use C++17 or Boost.

Do you believe these operations have a place in rcpputils? Should I make a `clamp.hpp` header just for it?

**Comment by Karsten1987** [comment]
I think a `clamp.hpp` header makes sense. We can then still introduce a common `math.hpp` header collecting all math functionality later on.

**Comment by emersonknapp** [comment]
Perhaps we should separate this out into a separate library, like rcppmath? I'd be fine with having that live here, but it may be useful to split right away in case it gets  a lot bigger (which it probably will, if we introduce it)

**Comment by Karsten1987** [comment]
I'd like the idea of making it its own library, but I think for the time being it can live in the `rcpputils` package.

**Comment by clalancette** [comment]
> I'd like the idea of making it its own library, but I think for the time being it can live in the `rcpputils` package.

Yeah, agreed.  If it starts to become too large, we can always think about splitting it out into a separate package/repository later.

**Comment by emersonknapp** [comment]
@v-lopez it looks like the consensus is to make a new CMake library target within the rcpputils package. This would probably use a new `include/rcppmath` directory instead of the `include/rcpputils` directory
