### ISSUE TITLE
Missing scope_exit from Foxy

### ISSUE THREAD

**Issue by methylDragon** [ros2/rcpputils#91]
The Foxy branch (and consequently the includes installed in `/opt/ros/foxy`) seem to be missing the [scope_exit](https://github.com/ros2/rcpputils/blob/master/include/rcpputils/scope_exit.hpp) header.

Is there any reason this was removed?

**Comment by hidmic** [comment]
@methylDragon that functionality was added post-Foxy (see https://github.com/ros2/rcpputils/pull/78). Though it only extends API, it'd be uncommon to backport a feature. CC @jacobperron.

**Comment by jacobperron** [comment]
@hidmic is correct, `scoped_exit.hpp` never existed in Foxy. If there's desire to backport https://github.com/ros2/rcpputils/pull/78 to the `foxy` branch, I'm not opposed if someone wants to do it.

**Comment by jacobperron** [comment]
@methylDragon If you'd like to make a backport PR, feel free to do so and I'm happy to review it. In the meantime, I'll just close this ticket since we don't plan to do it.
